# Generated by Django 5.0.6 on 2024-06-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
